name: Helpers
version: '${project.version}'
main: com.haroon.helpers.Main
api-version: 1.18
commands:
  mutechat:
    description: gives the player an item that mutes the chat
    aliases: mutethechat
  vanish:
    description: makes the player invisible
    aliases: vanishme
  banner:
    description: gives player a custom banner
    aliases: givebanner
  bannerhelmet:
    description: puts a banner on a player's head
    aliases: putabanneronmyhead
  punish:
    description: a command that punishes a player by kicking them, banning them, or temporarilly banning them
    aliases: punish
  enderchest:
    description: opens the enderchest as a gui
    aliases: enderchest
  test:
    description: says test in chat
    aliases: test


